### ISSUE TITLE
Allow for setting of lines during games

### ISSUE THREAD

**Issue by AnthonyDario** [skultimate5/LineCaller#1]
### Current flow idea
1. Create a game -> goes into game or home?
2. view the current game
	1. set the first line
		- injuries/subs
	2. say if line won or not
	3. repeat

**Comment by skultimate5** [comment]
Current Game Screen
- Need : Score for both teams, on O or D
- Maybe : How the past lines have done (i.e. 2-3-2 line on D got a break, O line #1 got broken)
